baseURL = "https://moritzheinzle.github.io/ac/"
title = "Course Notes"
defaultContentLanguage = "en"

disablePathToLower = true
enableGitInfo = false

[params]
  author = "Moritz Heinzle"
  githubRepo = "https://github.com/moritzheinzle/ac"
  subtitle = "Notes from academics"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
